[package]
name = "stylus-theme"
version = "0.1.0"
authors = ["Hyprcore Team <team@hyprcore.io>"]
description = "Global user styles for web browsers"
license = "MIT"

[[templates]]
target = "~/.config/hyprcore/generated/stylus/hyprcore.user.css"
content = """
/* ==UserStyle==
@name           Hyprcore Global
@namespace      github.com/ryugen/hyprcore
@version        1.0.0
@description    Global theme overrides generated by Hyprcore
@author         Hyprcore
==/UserStyle== */

@-moz-document regexp(".*") {
  :root {
    --hypr-bg: {{ colors.bg }};
    --hypr-fg: {{ colors.fg }};
    --hypr-primary: {{ colors.primary }};
    --hypr-secondary: {{ colors.secondary }};
    --hypr-success: {{ colors.success }};
    --hypr-error: {{ colors.error }};
    --hypr-warn: {{ colors.warn }};
    --hypr-info: {{ colors.info }};
  }

  /* Global Selection */
  ::selection {
    background-color: {{ colors.selection_bg }} !important;
    color: {{ colors.selection_fg }} !important;
  }

  /* Scrollbars (Webkit) */
  ::-webkit-scrollbar {
    width: 12px;
    height: 12px;
    background-color: {{ colors.bg }};
  }

  ::-webkit-scrollbar-thumb {
    background-color: {{ colors.primary }};
    border: 3px solid {{ colors.bg }};
    border-radius: 6px;
  }

  ::-webkit-scrollbar-thumb:hover {
    background-color: {{ colors.secondary }};
  }

  ::-webkit-scrollbar-corner {
    background-color: {{ colors.bg }};
  }
}
"""

[[templates]]
target = "~/.config/hyprcore/generated/stylus/hyprcore-stylus.json"
content = """
[
  {
    "enabled": true,
    "name": "Hyprcore Global",
    "sections": [
      {
        "code": ":root {\\n  --hypr-bg: {{ colors.bg }};\\n  --hypr-fg: {{ colors.fg }};\\n  --hypr-primary: {{ colors.primary }};\\n  --hypr-secondary: {{ colors.secondary }};\\n  --hypr-success: {{ colors.success }};\\n  --hypr-error: {{ colors.error }};\\n  --hypr-warn: {{ colors.warn }};\\n  --hypr-info: {{ colors.info }};\\n}\\n\\n/* Global Selection */\\n::selection {\\n  background-color: {{ colors.selection_bg }} !important;\\n  color: {{ colors.selection_fg }} !important;\\n}\\n\\n/* Scrollbars (Webkit) */\\n::-webkit-scrollbar {\\n  width: 12px;\\n  height: 12px;\\n  background-color: {{ colors.bg }};\\n}\\n\\n::-webkit-scrollbar-thumb {\\n  background-color: {{ colors.primary }};\\n  border: 3px solid {{ colors.bg }};\\n  border-radius: 6px;\\n}\\n\\n::-webkit-scrollbar-thumb:hover {\\n  background-color: {{ colors.secondary }};\\n}\\n\\n::-webkit-scrollbar-corner {\\n  background-color: {{ colors.bg }};\\n}",
        "urls": [],
        "urlPrefixes": [],
        "regexps": [
          ".*"
        ]
      }
    ]
  }
]
"""

[hooks]
# Optional hook
