/**
 * @file kitchn.h
 * @brief Kitchn FFI Interface - C bindings for the Kitchn library
 * 
 * Provides a stable C-ABI interface for configuration management,
 * logging, packaging, and ingredient processing.
 * 
 * @see https://github.com/ryugen/kitchn
 */

#ifndef KITCHN_H
#define KITCHN_H

/* Compiler feature detection and hardening macros */
#if defined(__GNUC__) || defined(__clang__)
  #define KITCHN_API __attribute__((visibility("default")))
  #define KITCHN_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
  #define KITCHN_NONNULL(...) __attribute__((nonnull(__VA_ARGS__)))
  #define KITCHN_DEPRECATED(msg) __attribute__((deprecated(msg)))
  #define KITCHN_PRINTF(fmt, args) __attribute__((format(printf, fmt, args)))
#elif defined(_MSC_VER)
  #define KITCHN_API __declspec(dllexport)
  #define KITCHN_WARN_UNUSED_RESULT _Check_return_
  #define KITCHN_NONNULL(...)
  #define KITCHN_DEPRECATED(msg) __declspec(deprecated(msg))
  #define KITCHN_PRINTF(fmt, args)
#else
  #define KITCHN_API
  #define KITCHN_WARN_UNUSED_RESULT
  #define KITCHN_NONNULL(...)
  #define KITCHN_DEPRECATED(msg)
  #define KITCHN_PRINTF(fmt, args)
#endif

/* Thread safety annotations (Clang only) */
#if defined(__clang__) && defined(__has_attribute)
  #if __has_attribute(capability)
    #define KITCHN_CAPABILITY(x) __attribute__((capability(x)))
    #define KITCHN_REQUIRES(...) __attribute__((requires_capability(__VA_ARGS__)))
    #define KITCHN_EXCLUDES(...) __attribute__((locks_excluded(__VA_ARGS__)))
  #endif
#endif
#ifndef KITCHN_CAPABILITY
  #define KITCHN_CAPABILITY(x)
  #define KITCHN_REQUIRES(...)
  #define KITCHN_EXCLUDES(...)
#endif

/* Null pointer check helper */
#define KITCHN_ASSERT_NOT_NULL(ptr) \
    do { if (!(ptr)) { return; } } while(0)
#define KITCHN_ASSERT_NOT_NULL_RET(ptr, ret) \
    do { if (!(ptr)) { return (ret); } } while(0)

/* Generated with cbindgen:0.29.2 */

/* AUTO-GENERATED by cbindgen - DO NOT EDIT */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Opaque context pointer (wraps Cookbook with error storage)
 */
typedef struct KitchnContext KitchnContext;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

struct KitchnContext *kitchn_context_new(void);

/**
 * # Safety
 *
 * This function is unsafe because it dereferences raw pointers.
 * * `ctx` must be a valid pointer to `KitchnContext` created by `kitchn_context_new`.
 */
void kitchn_context_free(struct KitchnContext *ctx);

/**
 * Copies the last error message into the provided buffer.
 * Returns the number of bytes written (excluding null terminator),
 * or -1 if the buffer was too small or no error exists.
 * # Safety
 *
 * This function is unsafe because it dereferences raw pointers.
 * * `ctx` must be a valid pointer to `KitchnContext` created by `kitchn_context_new`.
 * * `buffer` must be a valid pointer to a writable memory region of at least `len` bytes.
 */
int kitchn_get_last_error(struct KitchnContext *ctx, char *buffer, uintptr_t len);

/**
 * # Safety
 *
 * This function is unsafe because it dereferences raw pointers.
 * * `ctx` must be a valid pointer to `KitchnContext`.
 * * `name` must be a valid, null-terminated C string.
 */
void kitchn_context_set_app_name(struct KitchnContext *ctx, const char *name);

/**
 * # Safety
 *
 * This function is unsafe because it dereferences raw pointers.
 * * `ctx` must be a valid pointer to `KitchnContext`.
 * * `level`, `scope`, and `msg` must be valid, null-terminated C strings.
 */
void kitchn_log(struct KitchnContext *ctx, const char *level, const char *scope, const char *msg);

/**
 * # Safety
 *
 * This function is unsafe because it dereferences raw pointers.
 * * `ctx` must be a valid pointer to `KitchnContext`.
 * * `preset_key` must be a valid, null-terminated C string.
 * * `msg_override` can be null. If not null, must be valid, null-terminated C string.
 */
int kitchn_log_preset(struct KitchnContext *ctx, const char *preset_key, const char *msg_override);

/**
 * # Safety
 *
 * This function is unsafe because it dereferences raw pointers.
 * * `ctx` must be a valid pointer to `KitchnContext`.
 * * `src_dir` and `out_file` must be valid, null-terminated C strings.
 */
int kitchn_pack(struct KitchnContext *ctx, const char *src_dir, const char *out_file);

/**
 * # Safety
 *
 * This function is unsafe because it dereferences raw pointers.
 * * `ctx` must be a valid pointer to `KitchnContext`.
 * * `pkg_file` and `target_dir` must be valid, null-terminated C strings.
 */
int kitchn_unpack(struct KitchnContext *ctx, const char *pkg_file, const char *target_dir);

/**
 * # Safety
 *
 * This function is unsafe because it dereferences raw pointers.
 * * `ctx` must be a valid pointer to `KitchnContext`.
 * * `path` must be a valid, null-terminated C string.
 */
int kitchn_store(struct KitchnContext *ctx, const char *path);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

/* ABI version for runtime compatibility checks */
#define KITCHN_ABI_VERSION_MAJOR 0
#define KITCHN_ABI_VERSION_MINOR 1
#define KITCHN_ABI_VERSION_PATCH 1

/* End of kitchn.h */
#endif /* KITCHN_H */
